services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qBittorrent
      - 9000:80   # SpeedTest
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
      - 7878:7878 # Radarr
      - 8191:8191 # FlareSolverr
    volumes:
      - /docker/appdata/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES={{"Get this value from your ProtonVPN wireguard config file"}}
      - TZ=America/New_York

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8085
      - PUBLIC_IP=${PUBLIC_IP}
    volumes:
      - /docker/appdata/qbittorrent:/config
      - {{"Enter the location of your downloads folder"}}:/data/downloads
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'RUNNING HEALTHCHECK' && curl -m 5 -s ifconfig.co | grep -qv \"$PUBLIC_IP\" && echo 'HEALTHCHECK SUCCESS' || (echo 'HEALTHCHECK FAIL' && exit 1)"
        ]
      interval: 300s
      timeout: 60s
      retries: 1
      start_period: 15s

  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - SPEEDTEST_SCHEDULE=0 */2 * * *
      - TZ=America/New_York
      - DB_CONNECTION=sqlite
      - APP_KEY={{"Enter your API key from https://speedtest-tracker.dev/"}}
    volumes:
      - /docker/appdata/speedtest:/config
    restart: unless-stopped
    network_mode: "service:gluetun"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/appdata/sonarr/config:/config
      - /docker/appdata/sonarr/data/backup:/data/backup
      - {{"Enter the location of your data folder"}}:/data
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/appdata/radarr/config:/config
      - /docker/appdata/radarr/data/backup:/data/backup
      - {{"Enter the location of your data folder"}}:/data
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/appdata/prowlarr/config:/config
      - /docker/appdata/prowlarr/data/backup:/data/backup
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/New_York
    restart: unless-stopped
